---
title: "README"
author: "Jonathan Clarke"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Outline

This repository contains the associated code for downloading the data, executing the models, and producing the manuscript for a project taken during a course run by the Department of Biological Sciences, University of Cape Town. 

# Files

- 00_dataImport.R - R script to download data from Github (see the links coded in the script), and specify a function for ease of data subsetting.

- 01_SimpleWrapper.R - R script to call and fit Stan models to a selected period of time-series data. 

- 03_Manuscript.Rmd - Rmarkdown document to produce a write-up on the project, calling several model fits generated by 01_SimpleWrapper and saved to local storage. Also requires .csv files saved to local storage, which can easily be generated using the function specified in 00_dataImport.

- 04.1_Basic.stan - stan file for the convolution-only model described in the manuscript.

- 04.2_Scaling.stan - stan file for the input-scaling model described in the manuscript.

- 04.3_TimeVariant.stan - stan file for the time-variant IRF, input scaling model described in the manuscript.

- 04.4_TimeVariantTwo.stan - stan file for the time-variant IRF model described in the manuscript.